# Generated by Django 4.1.2 on 2022-10-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_something"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Something",
        ),
    ]
